### ISSUE TITLE
OpenDb() is required to be called at least once?

### ISSUE THREAD

**Issue by thepra** [nwestfall/BlazorDB#14]
I was wondering given that in the short use guide nothing does talk about it.

**Comment by tfrank7415** [comment]
@thepra `_dbFactory.GetDbManager(dbName);` must be called before your database(s) and store(s) are created in the browser. This is because _dbFactory.GetDbManager() calls BuildFromServices(). The BuildFromServices() method contains the logic that creates databases based on your configuration settings in Program.cs. See below. 
![BuildFromServices](https://user-images.githubusercontent.com/44216318/210116675-8c7ab557-a84a-4f9e-97d4-c628af50f7eb.PNG)
So you must call `_dbFactory.GetDbManager(dbName)` before your database(s) and store(s) will be created in the browser. 

Let me know if I need to explain something better.

**Comment by tfrank7415** [comment]
@nwestfall Can we close this issue?

**Comment by thepra** [comment]
So yes? For every DB operation it the Db should be opened.

**Comment by tfrank7415** [comment]
Good morning @thepra. Yes. The DB must be open to perform a db operation. But you do not need to open the DB before every operation. You only need an instance of IndexedDbManager which you can get with the following code `manager = await _dbFactory.GetDbManager(dbName)`. So you can make a call to `_dbFactory.GetDbManager(dbName)` in a class constructor or in some type of lifecycle method. See attached for an example in a razor component. 
![OpenDbExample](https://user-images.githubusercontent.com/44216318/210178311-dbf4d2e6-2a42-48ba-ad83-ea613e0d2624.PNG)

Once you have an instance of IndexedDbManager you can reuse it for each operation.
